version: '3.8'

services:
  sd-frontend:
    container_name: sd-frontend
    image: sd-frontend
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: ["yarn", "start"]

  sd-frontend-sb:
    container_name: sd-frontend-sb
    image: sd-frontend-sb
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    ports:
      - 6006:6006
    command: ["yarn", "storybook"]    
